Bug Fix: conflicting lines causing compile error
Assets\Scripts\Scene Management\States\GameplayState.cs(114,41): error CS1503: Argument 1: cannot convert from 'AudioPair' to 'UnityEngine.AudioClip'